/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author valenthina
 */
public class bocas extends javax.swing.JFrame {

    /**
     * Creates new form bocas
     */
    public bocas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/B1.png"))); // NOI18N
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 25, -1, -1));

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b5.png"))); // NOI18N
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
        });
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        l10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b10.png"))); // NOI18N
        l10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l10MouseClicked(evt);
            }
        });
        getContentPane().add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 212, -1, -1));

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b2.png"))); // NOI18N
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b8.png"))); // NOI18N
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
        });
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 106, -1, -1));

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b4.png"))); // NOI18N
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
        });
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 34, -1, -1));

        l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b9.png"))); // NOI18N
        l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l9MouseClicked(evt);
            }
        });
        getContentPane().add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 192, -1, -1));

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b3.png"))); // NOI18N
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b6.png"))); // NOI18N
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
        });
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 118, -1, -1));

        l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b7.png"))); // NOI18N
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l7MouseClicked(evt);
            }
        });
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 118, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-blanco-grande.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 680, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        
        Vista.Boca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/B1.png")));
        Vista.Boca1.setVisible(true);
        Archivos.ob.setBocas("boca1");
        this.dispose();
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
       
        Vista.Boca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b2.png")));
        Vista.Boca1.setVisible(true);
        Archivos.ob.setBocas("boca2");
        this.dispose();
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
  
        Vista.Boca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b3.png")));
        Vista.Boca1.setVisible(true);
         Archivos.ob.setBocas("boca3");
        this.dispose();
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
         
        Vista.Boca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b4.png")));
        Vista.Boca1.setVisible(true);
        Archivos.ob.setBocas("boca4");
        this.dispose();
    }//GEN-LAST:event_l4MouseClicked

    private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked
         
        Vista.Boca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b5.png")));
        Vista.Boca1.setVisible(true);
        Archivos.ob.setBocas("boca5");
        this.dispose();
    }//GEN-LAST:event_l5MouseClicked

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked
        
        Vista.Boca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b6.png")));
        Vista.Boca1.setVisible(true);
         Archivos.ob.setBocas("boca6");
        this.dispose();
    }//GEN-LAST:event_l6MouseClicked

    private void l7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseClicked
         
        Vista.Boca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b7.png")));
        Vista.Boca1.setVisible(true);
        Archivos.ob.setBocas("boca7");
        this.dispose();
    }//GEN-LAST:event_l7MouseClicked

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
         
        Vista.Boca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b8.png")));
        Vista.Boca1.setVisible(true);
        Archivos.ob.setBocas("boca8");
        this.dispose();
    }//GEN-LAST:event_l8MouseClicked

    private void l9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseClicked
         
        Vista.Boca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b9.png")));
        Vista.Boca1.setVisible(true);
        Archivos.ob.setBocas("boca9");
        this.dispose();
    }//GEN-LAST:event_l9MouseClicked

    private void l10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l10MouseClicked
         
        Vista.Boca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bocas/b10.png")));
        Vista.Boca1.setVisible(true);
        Archivos.ob.setBocas("boca10");
        this.dispose();
    }//GEN-LAST:event_l10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bocas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bocas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bocas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bocas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bocas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
