/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author valenthina
 */
public class cabellos extends javax.swing.JFrame {

    /**
     * Creates new form cabellos
     */
    public cabellos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello_pequeño/cb1.png"))); // NOI18N
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello_pequeño/cb2.png"))); // NOI18N
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello_pequeño/cb3.png"))); // NOI18N
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello_pequeño/cb4.png"))); // NOI18N
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
        });
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello_pequeño/cb5.png"))); // NOI18N
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
        });
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello_pequeño/cb6.png"))); // NOI18N
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
        });
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello_pequeño/cb7.png"))); // NOI18N
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l7MouseClicked(evt);
            }
        });
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello_pequeño/cb8.png"))); // NOI18N
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
        });
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello_pequeño/cb9.png"))); // NOI18N
        l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l9MouseClicked(evt);
            }
        });
        getContentPane().add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-blanco-grande.gif"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 710, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        
        Vista.cabello1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello/cb1.png")));
         Vista.cabello1.setVisible(true);
        Archivos.ob.setCabello("cabe1");
        this.dispose();
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        
        Vista.cabello1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello/cb2.png")));
        Vista.cabello1.setVisible(true);
         Archivos.ob.setCabello("cabe2");
        this.dispose();
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
       
        Vista.cabello1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello/cb3.png")));
        Vista.cabello1.setVisible(true);
         Archivos.ob.setCabello("cabe3");
        this.dispose();
    }//GEN-LAST:event_l3MouseClicked

    private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked
        
        Vista.cabello1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello/cb5.png")));
        Vista.cabello1.setVisible(true);
         Archivos.ob.setCabello("cabe5");
        this.dispose();
    }//GEN-LAST:event_l5MouseClicked

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
           
        Vista.cabello1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello/cb8.png")));
        Vista.cabello1.setVisible(true);
         Archivos.ob.setCabello("cabe8");
        this.dispose();
    }//GEN-LAST:event_l8MouseClicked

    private void l9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseClicked
         
        Vista.cabello1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello/cb9.png")));
        Vista.cabello1.setVisible(true);
         Archivos.ob.setCabello("cabe9");
        this.dispose();
    }//GEN-LAST:event_l9MouseClicked

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked
          
        Vista.cabello1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello/cb6.png")));
        Vista.cabello1.setVisible(true);
         Archivos.ob.setCabello("cabe6");
        this.dispose();
    }//GEN-LAST:event_l6MouseClicked

    private void l7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseClicked
     
        Vista.cabello1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello/cb7.png")));
        Vista.cabello1.setVisible(true);
         Archivos.ob.setCabello("cabe7");
        this.dispose();
    }//GEN-LAST:event_l7MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
       
        Vista.cabello1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabello/cb4.png")));
        Vista.cabello1.setVisible(true);
         Archivos.ob.setCabello("cabe4");
        this.dispose();
    }//GEN-LAST:event_l4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cabellos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cabellos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cabellos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cabellos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cabellos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
