
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author valenthina
 */
public class CrearDoc extends javax.swing.JFrame {

    /**
     * Creates new form CrearDoc
     */
    public CrearDoc() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Leelawadee UI", 2, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Crear Archivo");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, -1));

        l2.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText("Nombre");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 60, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 158, -1));

        l3.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Documento");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 158, -1));

        l4.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("Correo");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 158, -1));

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar azul.png"))); // NOI18N
        b1.setBorder(null);
        b1.setContentAreaFilled(false);
        b1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras azul.png"))); // NOI18N
        b2.setBorder(null);
        b2.setContentAreaFilled(false);
        b2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar azul.png"))); // NOI18N
        b3.setBorder(null);
        b3.setContentAreaFilled(false);
        b3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f8.1.jpg"))); // NOI18N
        fondo.setText("jLabel2");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        InterPrincipal2 ob = new InterPrincipal2();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
       //obtener informacion de las cajas de texto
       Vista obj = new Vista();
       
       
        String nom = t1.getText();
        String doc = t2.getText();
        String corr = t3.getText();
        
        
        
        
        
        if(t1.getText().equals("") || t2.getText().equals("") || t3.getText().equals("") ){
            
            JOptionPane.showMessageDialog(null," Digite los tres campos");
            
        }else{
            Archivos.ob.setNombre(nom);
            Archivos.ob.setDoc(doc);
            Archivos.ob.setEmail(corr);
            
            Archivos.ob.crearUsuario();
            
            t1.setText("");
            t2.setText("");
            t3.setText("");
            
            obj.setVisible(true);
            this.dispose();
            
            Hilos ob2 = new Hilos();
            ob2.start();
            
            
            
        }
        
        

    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
