

import java.awt.AWTException;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author valenthina
 */
public class Vista extends javax.swing.JFrame {

    
    public Vista() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boca1 = new javax.swing.JLabel();
        Ojo1 = new javax.swing.JLabel();
        cabello1 = new javax.swing.JLabel();
        Ore22 = new javax.swing.JLabel();
        Nariz1 = new javax.swing.JLabel();
        Cara1 = new javax.swing.JLabel();
        Cara = new javax.swing.JButton();
        Ojos = new javax.swing.JButton();
        Boca = new javax.swing.JButton();
        cabellos = new javax.swing.JButton();
        Narices = new javax.swing.JButton();
        Finalizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boca1.setVisible(false);
        Boca1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Boca1MouseDragged(evt);
            }
        });
        getContentPane().add(Boca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        Ojo1.setVisible(false);
        Ojo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Ojo1MouseDragged(evt);
            }
        });
        getContentPane().add(Ojo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        cabello1.setVisible(false);
        cabello1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cabello1MouseDragged(evt);
            }
        });
        getContentPane().add(cabello1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        Ore22.setVisible(false);
        Ore22.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Ore22MouseDragged(evt);
            }
        });
        getContentPane().add(Ore22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        Nariz1.setVisible(false);
        Nariz1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Nariz1MouseDragged(evt);
            }
        });
        getContentPane().add(Nariz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        Cara1.setVisible(false);
        Cara1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Cara1MouseDragged(evt);
            }
        });
        getContentPane().add(Cara1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        Cara.setBackground(new java.awt.Color(0, 0, 102));
        Cara.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        Cara.setForeground(new java.awt.Color(255, 255, 255));
        Cara.setText("Caras");
        Cara.setBorder(null);
        Cara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaraActionPerformed(evt);
            }
        });
        getContentPane().add(Cara, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));

        Ojos.setBackground(new java.awt.Color(0, 0, 102));
        Ojos.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        Ojos.setForeground(new java.awt.Color(255, 255, 255));
        Ojos.setText("Ojos");
        Ojos.setBorder(null);
        Ojos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OjosActionPerformed(evt);
            }
        });
        getContentPane().add(Ojos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        Boca.setBackground(new java.awt.Color(0, 0, 102));
        Boca.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        Boca.setForeground(new java.awt.Color(255, 255, 255));
        Boca.setText("Bocas");
        Boca.setBorder(null);
        Boca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BocaActionPerformed(evt);
            }
        });
        getContentPane().add(Boca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, -1));

        cabellos.setBackground(new java.awt.Color(0, 0, 102));
        cabellos.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        cabellos.setForeground(new java.awt.Color(255, 255, 255));
        cabellos.setText("cabellos");
        cabellos.setBorder(null);
        cabellos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabellosActionPerformed(evt);
            }
        });
        getContentPane().add(cabellos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, -1));

        Narices.setBackground(new java.awt.Color(0, 0, 102));
        Narices.setFont(new java.awt.Font("Leelawadee UI", 2, 14)); // NOI18N
        Narices.setForeground(new java.awt.Color(255, 255, 255));
        Narices.setText("Narices");
        Narices.setBorder(null);
        Narices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaricesActionPerformed(evt);
            }
        });
        getContentPane().add(Narices, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, -1));

        Finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar azul.png"))); // NOI18N
        Finalizar.setBorder(null);
        Finalizar.setContentAreaFilled(false);
        Finalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(Finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-blanco-grande.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 360, 510));

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vista.jpg"))); // NOI18N
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boca1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boca1MouseDragged
       Boca1.setLocation(
				Boca1.getX() + evt.getX() - Boca1.getWidth() / 2,
				Boca1.getY() + evt.getY() - Boca1.getHeight() / 2
				);
    }//GEN-LAST:event_Boca1MouseDragged

    private void Ojo1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ojo1MouseDragged
        Ojo1.setLocation(
				Ojo1.getX() + evt.getX() - Ojo1.getWidth() / 2,
				Ojo1.getY() + evt.getY() - Ojo1.getHeight() / 2
				);
    }//GEN-LAST:event_Ojo1MouseDragged

    private void Nariz1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nariz1MouseDragged
       Nariz1.setLocation(
				Nariz1.getX() + evt.getX() - Nariz1.getWidth() / 2,
				Nariz1.getY() + evt.getY() - Nariz1.getHeight() / 2
				); 
    }//GEN-LAST:event_Nariz1MouseDragged

    private void cabello1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabello1MouseDragged
       cabello1.setLocation(
				cabello1.getX() + evt.getX() - cabello1.getWidth() / 2,
				cabello1.getY() + evt.getY() - cabello1.getHeight() / 2
				);  
    }//GEN-LAST:event_cabello1MouseDragged

    private void Ore22MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ore22MouseDragged
       Ore22.setLocation(
				Ore22.getX() + evt.getX() - Ore22.getWidth() / 2,
				Ore22.getY() + evt.getY() - Ore22.getHeight() / 2
				);   
    }//GEN-LAST:event_Ore22MouseDragged

    private void Cara1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cara1MouseDragged
       Cara1.setLocation(
				Cara1.getX() + evt.getX() - Cara1.getWidth() / 2,
				Cara1.getY() + evt.getY() - Cara1.getHeight() / 2
				);  
    }//GEN-LAST:event_Cara1MouseDragged

    private void CaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaraActionPerformed
       caras1 ob = new caras1();
       ob.setVisible(true);
    }//GEN-LAST:event_CaraActionPerformed

    private void OjosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OjosActionPerformed
       ojos ob = new ojos();
       ob.setVisible(true);
    }//GEN-LAST:event_OjosActionPerformed

    private void BocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BocaActionPerformed
      bocas ob= new bocas();
      ob.setVisible(true);
    }//GEN-LAST:event_BocaActionPerformed

    private void cabellosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabellosActionPerformed
      cabellos ob= new cabellos();
      ob.setVisible(true);
    }//GEN-LAST:event_cabellosActionPerformed

    private void NaricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaricesActionPerformed
     nariz ob= new nariz();
      ob.setVisible(true);     
    }//GEN-LAST:event_NaricesActionPerformed

    private void FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarActionPerformed

        try{
           Robot robot = new Robot();
           BufferedImage image= robot.createScreenCapture(new Rectangle(500,110, 368, 508));
           ImageIO.write(image,"png", new File("C:\\Users\\valenthina\\Desktop\\ARCHIVOS\\captura.png"));
           
        }catch(AWTException e){
            e.printStackTrace();
        }catch(IOException e){
            e.printStackTrace();
        }
        Archivos ob = new Archivos();
        
        ob.pdf();
        ob.comparar();
        ob.identificar();
        ob.Correo();
        CrearDoc ob1 =new CrearDoc();
        ob1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_FinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boca;
    public static javax.swing.JLabel Boca1;
    private javax.swing.JButton Cara;
    public static javax.swing.JLabel Cara1;
    private javax.swing.JButton Finalizar;
    private javax.swing.JButton Narices;
    public static javax.swing.JLabel Nariz1;
    public static javax.swing.JLabel Ojo1;
    private javax.swing.JButton Ojos;
    private javax.swing.JLabel Ore22;
    public static javax.swing.JLabel cabello1;
    private javax.swing.JButton cabellos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables
}
